spring.application.name=controlstock
spring.datasource.url=jdbc:postgresql://localhost:5432/controlstockdb
spring.datasource.username=postgres
spring.datasource.password=Volterra1029
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.port=8080